### ISSUE TITLE
Failure to start Netdata: '/usr/bin/run.sh: Permission denied'

### ISSUE THREAD

**Issue by Onibus** [CryoRig/netdata-homeassistant-addon#9] opened 2023-07-17 00:13 UTC
HA Version: Home Assistant OS 2023.7.1
Netdata Addon version: 2.2.2
Other information: fairly fresh HAOS install. Only other addons worth mentioning are AdGuard Home and Advanced SSH/Terminal.

Installation of Netdata was successful. After configuring claim token/room and saving, I attempt to start Netdata addon. Shortly after, it stops. The event log shows the following:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
/run/s6/basedir/scripts/rc.init: line 69: /usr/bin/run.sh: Permission denied
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

Diving in to the docker image itself:
```
~ docker images
    REPOSITORY                                             TAG         IMAGE ID       CREATED        SIZE
    ghcr.io/cryorig/aarch64-netdata-homeassistant-addon    2.2.2       323b528201b2   4 days ago     299MB
 ~ docker run -it 323b528201b2 bash
bash-5.1# ./usr/bin/run.sh
    bash: ./usr/bin/run.sh: Permission denied
bash-5.1# ls -l /usr/bin/run.sh
    -rw-r--r--    1 root     root           369 Jul 12 13:12 /usr/bin/run.sh
bash-5.1# chmod +x /usr/bin/run.sh
bash-5.1# ./usr/bin/run.sh
    [23:58:22] INFO: Configuring Netdata...
    ./usr/bin/run.sh: line 3: /usr/bin/config_netdata.sh: Permission denied
bash-5.1# chmod +x /usr/bin/config_netdata.sh
bash-5.1# ./usr/bin/run.sh
    [23:59:02] INFO: Configuring Netdata...
    2023-07-16 23:59:02: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/opt/netdata/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
    2023-07-16 23:59:02: netdata INFO  : MAIN : Found 0 legacy dbengines, setting multidb diskspace to 256MB
    2023-07-16 23:59:02: netdata INFO  : MAIN : Created file '/opt/netdata/var/lib/netdata/dbengine_multihost_size' to store the computed value
```

From this point, I'm not able to troubleshoot as it seems the container doesn't have internet connection; I don't know enough about Docker to test further.

**Comment by CryoRig** [comment] 2023-07-18 14:27
I'll look at it this weekend, I won't get to it before then

**Comment by CryoRig** [comment] 2023-07-18 14:57
I can't reproduce this on my haos install...
Are you using the Netdata or Netdata DEV Addon?
The DEV had a permission issue which i just pushed a fix for (hopefully)

**Comment by Onibus** [comment] 2023-07-21 05:07
I tried out the DEV branch and it launched though stopped a moment later due to `sed: bad option in substitution expression`

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[01:05:09] INFO: Configuring Netdata...
2023-07-21 01:05:09: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/opt/netdata/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
2023-07-21 01:05:09: netdata INFO  : MAIN : Found 0 legacy dbengines, setting multidb diskspace to 256MB
2023-07-21 01:05:09: netdata INFO  : MAIN : Created file '/opt/netdata/var/lib/netdata/dbengine_multihost_size' to store the computed value
[01:05:12] INFO: Netdata configuration: set hostname to homeassistant
[01:05:12] INFO: Netdata configuration: set page_cache_size to 32
[01:05:12] INFO: Netdata configuration: set page_cache_size to 256
[01:05:13] INFO: Netdata configuration: set config path to null/config
sed: bad option in substitution expression
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by CryoRig** [comment] 2023-07-21 06:01
ah yes i forgot i played around with the config substitutions
give me the weekend and it should work again

**Comment by CryoRig** [comment] 2023-07-28 08:42
Sorry i forgot
don't have time currently, work is kinda flooding me...

**Comment by CryoRig** [comment] 2023-08-17 11:25
both Addons should be working again (Netdata and Netdata DEV)
Keep in mind that the Issues from here --> #1 are still valid

**Comment by CryoRig** [comment] 2023-09-06 10:06
Closing as i got no reaction after 3 weeks...

**Closed as completed by CryoRig** 2023-09-06 10:06 UTC
Labels: bug
